import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const [inputPath, outputDir] = process.argv.slice(2);
if (!inputPath || !outputDir) throw new Error("Uso: node build_telemetria_workbook.mjs input.json output_dir");
const payload = JSON.parse(await fs.readFile(inputPath, "utf8"));
const qaDir = path.dirname(inputPath);
const workbook = Workbook.create();
const sheet = workbook.worksheets.add("Telemetria");
sheet.showGridLines = false;
const matrix = [payload.columns, ...payload.rows.map((row) => payload.columns.map((column) => row[column] ?? null))];
const used = sheet.getRangeByIndexes(0, 0, matrix.length, payload.columns.length);
used.values = matrix;
used.format.font = { name: "Aptos", size: 10, color: "#1F2937" };
used.format.rowHeight = 20;
const header = sheet.getRangeByIndexes(0, 0, 1, payload.columns.length);
header.format = { fill: "#385723", font: { name: "Aptos Display", size: 10, bold: true, color: "#FFFFFF" }, horizontalAlignment: "center", verticalAlignment: "center", wrapText: true, borders: { preset: "outside", style: "medium", color: "#274117" } };
header.format.rowHeight = 34;
sheet.getRange("A:N").format.columnWidth = 16;
sheet.getRange("A:B").format.columnWidth = 20;
sheet.getRange("E:H").format.columnWidth = 23;
sheet.getRange(`C2:D${matrix.length}`).format.numberFormat = "0";
sheet.getRange(`I2:J${matrix.length}`).format.numberFormat = "0.0";
sheet.getRange(`K2:L${matrix.length}`).format.numberFormat = "0.0";
sheet.getRange(`M2:N${matrix.length}`).format.numberFormat = "0.000000";
sheet.freezePanes.freezeRows(1);
const table = sheet.tables.add(`A1:N${matrix.length}`, true, "TelemetriaCrudaTable");
table.style = "TableStyleMedium4";
table.showFilterButton = true;
table.showBandedRows = true;
await fs.mkdir(outputDir, { recursive: true });
const outputPath = path.join(outputDir, "telemetria_dispositivos.xlsx");
const xlsx = await SpreadsheetFile.exportXlsx(workbook);
await xlsx.save(outputPath);
const inspection = await workbook.inspect({ kind: "table", range: "Telemetria!A1:N8", include: "values,formulas", tableMaxRows: 8, tableMaxCols: 14, maxChars: 6000 });
await fs.writeFile(path.join(qaDir, "telemetria_inspection.ndjson"), inspection.ndjson, "utf8");
const preview = await workbook.render({ sheetName: "Telemetria", range: "A1:J24", scale: 1.5, format: "png" });
await fs.writeFile(path.join(qaDir, "telemetria_preview.png"), new Uint8Array(await preview.arrayBuffer()));
const bytes = await fs.readFile(outputPath);
const manifest = { source: "telemetria", synthetic: true, seed: payload.seed, rows: payload.rows.length, columns: payload.columns, injected_quality: { duplicate_imei: 6, unmatched_devices: 15, mixed_dates: true, missing_values: true }, sha256: crypto.createHash("sha256").update(bytes).digest("hex") };
await fs.writeFile(path.join(outputDir, "telemetria_dispositivos.manifest.json"), JSON.stringify(manifest, null, 2) + "\n", "utf8");
await fs.rm(`${outputPath}.inspect.ndjson`, { force: true });
